name: 'Monorepo container build action'
author: Ian Belcher
description: An action to build and push a docker container via a command
branding:
  color: 'blue'
  icon: 'anchor'
runs:
  # using: 'docker'
  # image: 'Dockerfile'
  using: 'composite'
  steps:
    - id: build-and-push
      run: ${{ github.action_path }}/entry-point.sh
      shell: bash
      env:
        INPUT_CONTAINER_NAME: ${{ inputs.container_name }}
        INPUT_DOCKER_REGISTRY: ${{ inputs.docker_registry }}
        INPUT_DOCKER_REGISTRY_PASSWORD: ${{ inputs.docker_registry_password }}
        INPUT_DOCKER_REGISTRY_USERNAME: ${{ inputs.docker_registry_username }}
        INPUT_COMMAND_TO_RUN: ${{ inputs.command_to_run }}
        INPUT_TAG_AS_LATEST: ${{ inputs.tag_as_latest }}
inputs:
  container_name:
    description: The name of the container that this action is building
    required: true
  command_to_run:
    description: The command to run to build the container
    required: true
  docker_registry:
    description: The registry to use. This is likely in the form my-registry.domain.com:4000 or similar
    required: false
    default: ''
  docker_registry_username:
    description: The username of the registry user
    required: false
  docker_registry_password:
    description: The password of the registry user
    required: false
  tag_as_latest:
    description: Whether or not to tag the image as latest. "yes" or "no". Defaults to "yes".
    required: false
    default: 'yes'
outputs:
  IMAGE_SHA:
    description: The SHA of the pushed image
    value: ${{ steps.build-and-push.outputs.IMAGE_SHA }}
  IMAGE_URL:
    description: The full URL of the pushed image
    value: ${{ steps.build-and-push.outputs.IMAGE_URL }}
