name: 'Monorepo container build action'
author: Ian Belcher
description: An action to build and push a docker container via a command
branding:
  color: 'blue'
  icon: 'anchor'
runs:
  # using: 'docker'
  # image: 'Dockerfile'
  using: "composite"
  steps: 
    - run: . entry-point.sh
      shell: bash
inputs:
  container_name:
    description: The name of the container that this action is building
    required: true
  command_to_run:
    description: The command to run to build the container
    required: true
  docker_registry:
    description: The registry to use. This is likely in the form my-registry.domain.com:4000 or similar
    required: false
    default: ''
  docker_registry_username:
    description: The username of the registry user
    required: false
  docker_registry_password:
    description: The password of the registry user
    required: false
  stage:
    description: The CI/CD stage we are building e.g. production or staging or other
    required: true
outputs:
  IMAGE_SHA:
    description: The SHA of the pushed image
  IMAGE_URL:
    description: The full URL of the pushed image